name: devops test

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: get code from github
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ REMOTE_HOST }}
        username: ${{ REMOTE_USER }}
        key: ${{ KEY }}
        port: ${{ PORT }}
        script: |
          echo test > /tmp/abcd
    
