name: devops test

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: get code from github
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ SECRETS_REMOTE_HOST }}
        username: ${{ SECRETS_REMOTE_USER }}
        key: ${{ SECRETS_SSH_KEY }}
        port: ${{ SECRETS_REMOTE_PORT }}
        script: |
          echo test > /tmp/abcd
    
